trained_model_dir = 'trained_model'
le_file = 'le.sav'
selection_file_log = 'sel_pipe.sav'
selection_file_lgb = 'sel_lgb.sav'
selection_file_svc = 'sel_svm.sav'
pipe_log_file = 'log.sav'
svc_pipe_file = 'svm.sav'
lgb_file = 'lgb.sav'
